---
- name: Setup project with Git, copy configuration files, run app server

  # Specify the hosts you want to target
  hosts: appserver

  remote_user: team

  vars:
    projects_root: /home/team
    project_repo_url: git@github.com:brainless/solvex.git
    python_path: /usr/bin/python3
    system_packages: ["git"]
    project_name: "bnb_solvex"
    build_folder_owner: team
    build_folder_group: "www-data"

  tasks:
    - name: Install required system packages
      become: yes
      become_user: root
      apt: name={{ system_packages }} state=latest

    - name: Create Projects directory
      file:
        path: "{{ projects_root }}"
        state: directory

    - name: Clone project repo
      git:
        repo: "{{ project_repo_url }}"
        accept_hostkey: yes
        dest: "{{ projects_root }}/{{ project_name }}"
        version: develop

    - name: Install/update Python requirements for backend
      pip:
        requirements: "{{ projects_root }}/{{ project_name }}/backend/requirements.txt"
        chdir: "{{ projects_root }}/{{ project_name }}/backend"
        virtualenv: "{{ projects_root }}/{{ project_name }}/backend/.venv"
        virtualenv_command: "python3 -m virtualenv"

    - name: Copy gunicorn config files
      copy:
        src: "{{ item }}"
        dest: "/etc/systemd/system/"
        remote_src: yes
      with_items:
        - "{{ projects_root }}/{{ project_name }}/system/gunicorn/{{ project_name }}.service"
        - "{{ projects_root }}/{{ project_name }}/system/gunicorn/{{ project_name }}.socket"
      become: yes
      become_user: "root"

    - name: Copy nginx config files
      copy:
        src: "{{ item }}"
        dest: "/etc/nginx/sites-available/"
        remote_src: yes
      with_items:
        - "{{ projects_root }}/{{ project_name }}/system/nginx/www_{{ project_name }}_fun.conf"
        - "{{ projects_root }}/{{ project_name }}/system/nginx/{{ project_name }}_fun.conf"
      become: yes
      become_user: "root"

    - name: Create static content directory
      file:
        path: "/var/www/html/{{ project_name }}"
        state: directory
        owner: "{{ build_folder_owner }}"
        group: "{{ build_folder_group }}"
      become: yes
      become_user: "root"

    - name: Symlink nginx config files to sites-enabled
      file:
        src: "/etc/nginx/sites-available/{{ item }}"
        dest: "/etc/nginx/sites-enabled/{{ item }}"
        state: link
      with_items:
        - "www_{{ project_name }}_fun.conf"
        - "{{ project_name }}_fun.conf"
      become: yes
      become_user: "root"

    - name: Enable gunicorn to start on boot
      become: yes
      become_user: root
      systemd:
        name: "{{ project_name }}"
        enabled: yes

    - name: Start gunicorn server
      become: yes
      become_user: root
      systemd:
        name: "{{ project_name }}"
        state: started

    - name: Set migrations versioning for database
      command:
        chdir: "{{ projects_root }}/{{ project_name }}/backend"
        cmd: "{{ projects_root }}/{{ project_name }}/backend/.venv/bin/python migrations.py version_control"

    - name: Run migrations for database
      command:
        chdir: "{{ projects_root }}/{{ project_name }}/backend"
        cmd: "{{ projects_root }}/{{ project_name }}/backend/.venv/bin/python migrations.py upgrade"
